# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\清华 自96\学习\大三秋\人工智能基础\作业\project1\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 434)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CardNumBox = QtWidgets.QSpinBox(self.centralwidget)
        self.CardNumBox.setGeometry(QtCore.QRect(400, 180, 42, 22))
        self.CardNumBox.setMinimum(1)
        self.CardNumBox.setMaximum(54)
        self.CardNumBox.setProperty("value", 1)
        self.CardNumBox.setObjectName("CardNumBox")
        self.CardWidget = QtWidgets.QWidget(self.centralwidget)
        self.CardWidget.setGeometry(QtCore.QRect(80, 280, 301, 51))
        self.CardWidget.setObjectName("CardWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "斗地主"))
